# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Foodics' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Foodics
    pod 'Alamofire'
    pod 'SVProgressHUD'
    pod 'SDWebImage', '~> 5.0'
end
